.MODEL SMALL
.STACK 100H
.DATA
 ;Welcome messages and other variables
 WELCOMEMSG DB 'WELCOME TO  PROGRAM$'
 SECONDMSG DB 'MY NAME IS AKIB$'
.CODE
MAIN PROC
    ;SHOW WELCOME MESSAGE AND SECOND MESSAGE  
    MOV AX, @DATA
    MOV DS, AX
    ;WELCOME MESSAGE
    MOV AH,9
    LEA DX,WELCOMEMSG
    INT 21H
    ;PRINT NEW LINE
    CALL NEWLINE
    MOV AH,9
    LEA DX,SECONDMSG
    INT 21H
    
    ;EXIT TO DOS LABEL
    EXITTODOS:
    MOV AX,4CH
    INT 21H
MAIN ENDP
;OTHER PROCEDURES/FUNCTIONS
;NEW LINE PROC
NEWLINE PROC
    MOV AH,2
    MOV DL,0DH
    INT 21H
    ;LINEFEED
    MOV DL,0AH
    INT 21H
NEWLINE ENDP
END MAIN

